// cartActionTypes.js
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const FETCH_CART_SUCCESS = ' FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = ' FETCH_CART_FAILURE';
export const UPDATE_PRODUCT_IN_CART = ' UPDATE_PRODUCT_IN_CART';


