// actionTypes
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAILURE = 'FETCH_PRODUCTS_DETAILS_FAILURE';
export const SAVE_CART_ITEMS_SUCCESS = 'SAVE_CART_ITEMS_SUCCESS';
export const SAVE_CART_ITEMS_FAILURE = 'SAVE_CART_ITEMS_FAILURE';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';

